/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apresentacao;
import persistencia.EntradaEstoqueDAO;
import negocio.Produto;
import persistencia.ProdutoDAO;
import javax.swing.JOptionPane;
import java.util.List;
import persistencia.ProdutoDAO;
import negocio.Produto;
import negocio.Fornecedor;
import persistencia.FornecedorDAO;
import javax.swing.JOptionPane;
import negocio.Funcionario;
import persistencia.FuncionarioDAO;




/**
 *
 * @author Otávio
 */
public class TelaEntradaEstoque extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEntradaEstoque.class.getName());

    /**
     * Creates new form TelaEntradaEstoque
     */
    public TelaEntradaEstoque() {
        
        initComponents();
        carregarProdutos();
        carregarFornecedores();
       
        CustoTotalText.setEditable(false);
        TxtQuantidadeProduto.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        private void atualizarCusto() {
            String texto = TxtQuantidadeProduto.getText().trim();

            if (texto.isEmpty()) {
                CustoTotalText.setText("0");
                return;
            }

            try {
                int qtd = Integer.parseInt(texto);
                int custo = qtd * 2; 
                CustoTotalText.setText(String.valueOf(custo));
            } catch (NumberFormatException e) {
                CustoTotalText.setText("0");
            }
        }

        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) {
            atualizarCusto();
        }

        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) {
            atualizarCusto();
        }

        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) {
            atualizarCusto();
        }
    });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CbProduto = new javax.swing.JComboBox<>();
        CbFornecedor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CbFuncionario = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        TxtQuantidadeProduto = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        CustoTotalText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnSalvarEntrada = new javax.swing.JButton();
        BtnRtornar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  produto");

        CbProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbProduto.addActionListener(this::CbProdutoActionPerformed);

        CbFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbFornecedor.addActionListener(this::CbFornecedorActionPerformed);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("         fornecedor ");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("funcionario");

        CbFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CbFuncionario.addActionListener(this::CbFuncionarioActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(CbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(CbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(71, 71, 71))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        TxtQuantidadeProduto.addActionListener(this::TxtQuantidadeProdutoActionPerformed);

        jTextField1.setText("jTextField1");

        CustoTotalText.addActionListener(this::CustoTotalTextActionPerformed);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("quantidade");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("    data");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("cursto total:");

        BtnSalvarEntrada.setBackground(new java.awt.Color(0, 0, 0));
        BtnSalvarEntrada.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtnSalvarEntrada.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalvarEntrada.setText("Adicionar");
        BtnSalvarEntrada.addActionListener(this::BtnSalvarEntradaActionPerformed);

        BtnRtornar.setBackground(new java.awt.Color(0, 0, 0));
        BtnRtornar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtnRtornar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRtornar.setText("retornar");
        BtnRtornar.addActionListener(this::BtnRtornarActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(TxtQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(CustoTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnRtornar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSalvarEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRtornar))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustoTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalvarEntrada)
                        .addGap(14, 14, 14))))
        );

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Entrada de Estoque");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbProdutoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CbProdutoActionPerformed

    private void CbFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbFornecedorActionPerformed

    private void TxtQuantidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtQuantidadeProdutoActionPerformed
        // TODO add your handling code here:
         String texto = TxtQuantidadeProduto.getText();
       if (texto.isEmpty()) {
        return;
    }

    // Verifica se é inteiro (0–9 repetido)
    if (texto.matches("\\d+")) {
        quantidade_produtos_chegados = Integer.parseInt(texto);
    } else {
        // Mensagem de erro
        JOptionPane.showMessageDialog(this, "Valor inválido! Digite apenas números inteiros.");
        
        // Limpa o campo
        TxtQuantidadeProduto.setText("");

        // Opcional: mantém o cursor lá
        TxtQuantidadeProduto.requestFocus();

        // Não salva nada
        quantidade_produtos_chegados = 0;
    }
    }//GEN-LAST:event_TxtQuantidadeProdutoActionPerformed

    private void CustoTotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustoTotalTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CustoTotalTextActionPerformed

    private void BtnSalvarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarEntradaActionPerformed
        // TODO add your handling code here:
        try {
        // 1. Pegar produto selecionado do ComboBox
        Produto produtoSelecionado = (Produto) CbProduto.getSelectedItem();

        if (produtoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um produto.");
            return;
        }

        // 2. Ler a quantidade digitada no campo
        int qtdAdicionar = Integer.parseInt(TxtQuantidadeProduto.getText());

        if (qtdAdicionar <= 0) {
            JOptionPane.showMessageDialog(this, "Digite uma quantidade válida.");
            return;
        }
        double preco = produtoSelecionado.getPreco();
        double custoTotal = preco * qtdAdicionar;
        CustoTotalText.setText(String.valueOf(custoTotal));


        // 3. Atualizar no banco (somar ao estoque atual)
        ProdutoDAO dao = new ProdutoDAO();
        dao.adicionarEstoque(produtoSelecionado.getIdProduto(), qtdAdicionar);
        EntradaEstoqueDAO entradaDAO = new EntradaEstoqueDAO();

        int idProduto = produtoSelecionado.getIdProduto();
        int idFornecedor = CbFornecedor.getSelectedIndex() + 1; // AJUSTAR depois se necessário
        int idFuncionario = CbFuncionario.getSelectedIndex() + 1; // AJUSTAR depois se necessário

        entradaDAO.registrarEntrada(
                idProduto,
                idFornecedor,
                idFuncionario,
                qtdAdicionar,
                custoTotal
        );

        // 4. Mensagem ao usuário
        JOptionPane.showMessageDialog(this,
            "Estoque atualizado com sucesso!\n" +
            "Produto: " + produtoSelecionado.getNome() + "\n" +
            "Quantidade adicionada: " + qtdAdicionar);

        // 5. Limpar campo de quantidade
        TxtQuantidadeProduto.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Digite apenas números na quantidade.");
    }

    }//GEN-LAST:event_BtnSalvarEntradaActionPerformed

    private void CbFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbFuncionarioActionPerformed


    }//GEN-LAST:event_CbFuncionarioActionPerformed

    private void BtnRtornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRtornarActionPerformed
        // TODO add your handling code here:
     TelaMenu menu = new TelaMenu();  
    menu.setVisible(true);           
    this.dispose();
    }//GEN-LAST:event_BtnRtornarActionPerformed
private void carregarProdutos() {
    ProdutoDAO dao = new ProdutoDAO();
    List<Object> lista = dao.getAll();

    CbProduto.removeAllItems();

    for (Object obj : lista) {
        Produto p = (Produto) obj;
        CbProduto.addItem(p.getNome());  // apenas nome
    }
}
private void carregarFornecedores() {
    FornecedorDAO dao = new FornecedorDAO();
    List<Fornecedor> lista = dao.listarTodos();

    CbFornecedor.removeAllItems(); // limpa o combobox

    for (Fornecedor f : lista) {
        CbFornecedor.addItem(f.getNome()); // apenas o nome no combobox
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaEntradaEstoque().setVisible(true));
    }
    private int quantidade_produtos_chegados;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRtornar;
    private javax.swing.JButton BtnSalvarEntrada;
    private javax.swing.JComboBox<String> CbFornecedor;
    private javax.swing.JComboBox<String> CbFuncionario;
    private javax.swing.JComboBox<String> CbProduto;
    private javax.swing.JTextField CustoTotalText;
    private javax.swing.JTextField TxtQuantidadeProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
